### PR TITLE
Change Square Crypto to Spiral

### PR DESCRIPTION
**Pull request by MarnixCroes**
Square Crypto is now Spiral

### CODE REVIEW

**Comment by sr-gi** [comment]
Hey @MarnixCroes, thanks for the contribution.

The logo should also be updated (and the old one removed).

You can get the svg for the new logo [here](https://spiral.xyz/img/logo-107fbbb3e6ab7dd846bb56070511bc79.svg).

**Comment by MarnixCroes** [comment]
@sr-gi Awesome, thanks!
Should be fixed now

**Comment by sr-gi** [comment]
Last two commits can be squashed. The rest looks good.

PS: You could actually squash it all in a single commit tbh, given how small of a change this is.

**Comment by sr-gi** [comment]
@MarnixCroes can you squash the commits? This is ready to be merged once done.

**Comment by MarnixCroes** [comment]
> @MarnixCroes can you squash the commits?

Fixed now. Thanks for the patience

**Pull request merged**
